language: node_js
node_js:
  - "10"
dist: trusty 
sudo: required
addons:
  firefox: "65.0"
cache:
  directories:
    - node_modules
script:
  - npm run build && npm run test
notifications:
  email:
    on_success: never
    on_failure: always