language: node_js
node_js:
  - "0.10"
addons:
  chrome: stable
branches:
  only:
    - master
git:
  depth: 1
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
script:
  - npm run test
notifications:
  email:
    on_success: never
    on_failure: always