language: node_js
node_js:
  - "7"
addons:
  chrome: stable
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run build && npm run test
notifications:
  email:
    on_success: never
    on_failure: always