language: node_js
node_js:
  - "iojs"
  - "7"
dist: trusty,
addons:
    chrome: stable
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - npm test
after_success:
  - npm run typedoc