language: node_js
node_js:
  - "7"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
cache:
  directories:
    - node_modules
script:
  - npm run build && npm run test
notifications:
  email:
    on_success: never
    on_failure: always