language: node_js
node_js:
  - "7"
addons:
  chrome: stable
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm run build && npm run test
notifications:
  email:
    on_success: never
    on_failure: always